### ISSUE TITLE
Dropping Java imports in favor of R packages?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/SkeletonCohortCharacterization#5]
The skeleton now includes FeatureExtraction and SqlRender both as R packages (see DESCRIPTION) and as Java libraries (see inst/java).  Why can't this skeleton be written as pure R? 

The resulting R package is very big, and I don't think it is a good idea to have such big skeletons in Hydra.

**Comment by wivern** [comment]
The primary logic was implemented in Java and I'm not sure that would be easy to translate it to pure R. But at least we can remove redundant dependencies to reduce package size.

**Comment by chrisknoll** [comment]
I've asked this question many times, but I'll ask it again:

Why is this repo called 'skeleton'?  Is it supposed to house a java library that is shared across Arachne, WebAPI, and also callable from R (via rJava), or is it a repository that is solely an R package?  If you rewrite the characterization logic in pure R, how will we invoke the characterization logic from WebAPI?  Only via something like execution engine?

**Comment by schuemie** [comment]
If I understand correctly there's characterization logic in WebAPI that is not in FeatureExtraction. If so, what logic is it? Knowing that might make it easier to understand how to best organize it.

For example, perhaps it makes sense to incorporate this logic in FeatureExtraction. Or maybe there needs to be a new R package called 'Characterization'?

**Comment by chrisknoll** [comment]
I believe the characterization logic that is not in FeatureExtraction relates to FeatureCriteria.  So, on the WebAPI side, some of the work is offloaded to the FeatureExtraction library (we call these 'presets' and other work is handled by calculating prevalence by doing something akin to an 'inclusion rule'.  We also create 'statistic groups' also using criteria (where the person is put into the group based on meeting a Criteria, and overall prevalence is based on that sub-group).  I'm sure it would be a great feature of FeatureExtraction to be able to accept those criteria features as inputs to a feature analysis, but I don't think it's connected that way.
